# docker-compose -f spark_cluster_compose.yml up --scale spark-worker=2 -d
# docker-compose -f spark_cluster_compose.yml down
version: "3.3"
services:
  spark-master:
    image: dataismus/spark_node:latest
    build:
      dockerfile: ./spark_node_Dockerfile
      context: .
    container_name: spark-master
    hostname: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    networks:
      - spark_cluster
    # env_file: 
    #   - ./cluster-env.env
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_MASTER_LOG=/spark/logs
    # CANNOT "$" env VARIABLES IN THS "command". ENV Variables set here will only be unwrapped INSIDE the container
    # command: /spark/bin/spark-class org.apache.spark.deploy.master.Master --ip $SPARK_LOCAL_IP --port $SPARK_MASTER_PORT --webui-port $SPARK_MASTER_WEBUI_PORT
    command: /spark/bin/spark-class org.apache.spark.deploy.master.Master --ip spark-master --port 7077 --webui-port 8080
    # command: "/start-master.sh"
  spark-worker:
    image: dataismus/spark_node:latest
    build:
      dockerfile: ./spark_node_Dockerfile
      context: .
    depends_on:
      - spark-master
    ports:
      - 8081
    networks:
      - spark_cluster
    # env_file:
    #   - ./cluster-env.env
    environment:
      # - SPARK_LOCAL_IP=spark-master
      # - SPARK_MASTER_PORT=7077
      # - SPARK_MASTER=spark://SPARK_LOCAL_IP:SPARK_MASTER_PORT
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_LOG=/spark/logs
    # command: /spark/bin/spark-class org.apache.spark.deploy.worker.Worker --webui-port $SPARK_WORKER_WEBUI_PORT $SPARK_MASTER
    command: /spark/bin/spark-class org.apache.spark.deploy.worker.Worker --webui-port 8081 spark://spark-master:7077
    # command: "/start-worker.sh"
networks:  
  spark_cluster:
    driver: bridge
    ipam:
      driver: default